### ISSUE TITLE
Consider disable logging in S3ClientRequest for binary uploads

### ISSUE THREAD

**Issue by jklingsporn** [hubrick/vertx-s3-client#15]
Hi,
first of all, thanks for sharing this library, it helps me a lot!

Now to the issue: I tested your library while uploading a video-file of about ~8 MB file size. Because in development, I've set log level to DEBUG, it prints out a String-representation of the binary to the console which made the IDE crash. It took me a while to get behind the reason. What I did to overcome the issue, is setting log-level to INFO for the `S3ClientRequest` logger. 
My suggestion is to cap/truncate the log-output if it exceeds a certain threshold and maybe trace the full output.

**Comment by eemmiirr** [comment]
@jklingsporn yes the problem happens only when you have a debug level eneabled on the client and upload a big file. Tryied to just putput the first N bytes but the problem is when you have a multipart you don't know which part is for instance json and which binary data. So it can happen that you output the binary data and strip away the json which you are interested in. This debug level was mostly used for development and INFO is more then good for usage since every request is logged with it headers. So i would suggest just switch it to INFO

**Comment by jklingsporn** [comment]
I'm fine with switching to INFO for this logger, however you should mention it somewhere in the readme. I was about to give up on this library ("looks good, doesn't work") until I figured out it was just the output that the IDE freezed. Maybe other users experience the same issue and are not using your lib because of that.

**Comment by eemmiirr** [comment]
@jklingsporn yea makes apsolutely sense. Will try to figure out a better logging

**Comment by eemmiirr** [comment]
@jklingsporn you can use version 3.3.1. It has autotruncate for log outputs longer then 10000 characters
